export interface BlogPost {
  id: string
  title: string
  excerpt: string
  category: string
  branch: string
  date: string
  readTime: string
  author: string
  heroImage?: string
  heroVideo?: string
}

export const blogCategories = [
  "All",
  "Artificial Intelligence",
  "Drone Technology",
  "Cloud Computing",
  "LMS & EdTech",
]

export const blogPosts: BlogPost[] = [
  // ARTIFICIAL INTELLIGENCE (12 posts)
  {
    id: "ai-agriculture-transformation",
    title: "AI in Agriculture: Transforming India's Farming Landscape",
    excerpt: "Discover how AI-powered analytics, crop monitoring, and predictive models are revolutionizing agricultural productivity across Indian farms.",
    category: "Artificial Intelligence",
    branch: "AI in Agriculture",
    date: "2026-01-15",
    readTime: "6 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "ai-healthcare-detection",
    title: "AI-Driven Healthcare: Early Disease Detection Systems",
    excerpt: "Explore how computer vision and machine learning enable rapid medical imaging analysis and predictive diagnostics in modern healthcare.",
    category: "Artificial Intelligence",
    branch: "AI in Healthcare",
    date: "2026-01-12",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "computer-vision-applications",
    title: "Computer Vision Applications: From Theory to Practice",
    excerpt: "Deep dive into real-world computer vision implementations including object detection, facial recognition, and quality control systems.",
    category: "Artificial Intelligence",
    branch: "Computer Vision",
    date: "2026-01-08",
    readTime: "8 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1555255707-c07966088b7b?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "generative-ai-future",
    title: "Generative AI: The Future of Content Creation",
    excerpt: "Understanding how generative models are reshaping creative industries, from text to images and beyond.",
    category: "Artificial Intelligence",
    branch: "Generative AI",
    date: "2026-01-05",
    readTime: "6 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "ai-model-training",
    title: "AI Model Training: Best Practices for Production Systems",
    excerpt: "Comprehensive guide to training, validating, and deploying machine learning models at scale with optimal performance.",
    category: "Artificial Intelligence",
    branch: "AI Model Training",
    date: "2025-12-28",
    readTime: "9 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "intelligent-automation",
    title: "Intelligent Automation: AI-Powered Workflow Optimization",
    excerpt: "How businesses leverage AI to automate complex processes, reduce costs, and enhance operational efficiency.",
    category: "Artificial Intelligence",
    branch: "AI Automation",
    date: "2025-12-22",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "edge-ai-processing",
    title: "Edge AI: Processing Intelligence at the Source",
    excerpt: "Exploring edge computing combined with AI for real-time decision making in IoT devices and embedded systems.",
    category: "Artificial Intelligence",
    branch: "Edge AI",
    date: "2025-12-18",
    readTime: "6 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "ai-ethics-responsibility",
    title: "AI Ethics: Building Responsible AI Systems",
    excerpt: "Navigate the ethical considerations, bias mitigation, and transparency requirements in modern AI development.",
    category: "Artificial Intelligence",
    branch: "AI Ethics",
    date: "2025-12-12",
    readTime: "8 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "ai-iot-integration",
    title: "AI + IoT: The Smart Connected Future",
    excerpt: "How artificial intelligence enhances IoT ecosystems for predictive maintenance, smart homes, and industrial automation.",
    category: "Artificial Intelligence",
    branch: "AI + IoT",
    date: "2025-12-08",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "ai-smart-cities",
    title: "AI for Smart Cities: Urban Intelligence Revolution",
    excerpt: "Transforming urban infrastructure with AI-driven traffic management, waste optimization, and energy efficiency systems.",
    category: "Artificial Intelligence",
    branch: "AI for Smart Cities",
    date: "2025-12-02",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "nlp-communication",
    title: "Natural Language Processing: Human-AI Communication",
    excerpt: "Advanced NLP techniques powering chatbots, sentiment analysis, and language translation in enterprise applications.",
    category: "Artificial Intelligence",
    branch: "NLP",
    date: "2025-11-25",
    readTime: "8 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "ai-predictive-analytics",
    title: "AI-Powered Predictive Analytics for Business Intelligence",
    excerpt: "Leverage AI-driven forecasting models to anticipate market trends, customer behavior, and business outcomes.",
    category: "Artificial Intelligence",
    branch: "Predictive Analytics",
    date: "2025-11-20",
    readTime: "6 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=900&h=600&fit=crop&auto=format",
  },

  // DRONE TECHNOLOGY (12 posts)
  {
    id: "precision-farming-drones",
    title: "Precision Farming Drones: Maximizing Crop Yields",
    excerpt: "How agricultural drones equipped with multispectral sensors enable targeted interventions for optimal crop health.",
    category: "Drone Technology",
    branch: "Precision Farming Drones",
    date: "2026-01-10",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "drone-surveillance-mapping",
    title: "Drone Surveillance & Terrain Mapping Technologies",
    excerpt: "Advanced aerial mapping solutions for infrastructure monitoring, land surveys, and disaster response operations.",
    category: "Drone Technology",
    branch: "Surveillance & Mapping",
    date: "2026-01-06",
    readTime: "6 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "make-in-india-drones",
    title: "Make in India: Drone Manufacturing Excellence",
    excerpt: "Building world-class drones domestically—from design and component sourcing to quality assurance and certification.",
    category: "Drone Technology",
    branch: "Drone Manufacturing",
    date: "2026-01-03",
    readTime: "8 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "uav-regulations-india",
    title: "UAV Regulations in India: Compliance & Certification",
    excerpt: "Navigate DGCA guidelines, drone pilot licensing, and regulatory frameworks for commercial UAV operations.",
    category: "Drone Technology",
    branch: "UAV Regulations",
    date: "2025-12-30",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1579829366248-204fe8413f31?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "autonomous-drones",
    title: "Autonomous Drones: Self-Flying Intelligence",
    excerpt: "Cutting-edge autonomous navigation systems using AI, computer vision, and GPS-denied environment capabilities.",
    category: "Drone Technology",
    branch: "Autonomous Drones",
    date: "2025-12-25",
    readTime: "8 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "drone-swarm-technology",
    title: "Drone Swarm Technology: Coordinated Aerial Intelligence",
    excerpt: "Multi-drone coordination algorithms enabling synchronized operations for search, rescue, and large-scale monitoring.",
    category: "Drone Technology",
    branch: "Drone Swarm Technology",
    date: "2025-12-20",
    readTime: "9 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "ai-powered-drones",
    title: "AI-Powered Drones: Next-Gen Aerial Analytics",
    excerpt: "Integration of deep learning models for real-time object detection, tracking, and decision-making in flight.",
    category: "Drone Technology",
    branch: "AI-Powered Drones",
    date: "2025-12-15",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "defense-drones",
    title: "Defense Applications: Drones in National Security",
    excerpt: "Tactical UAV deployment for border surveillance, reconnaissance, and strategic defense operations.",
    category: "Drone Technology",
    branch: "Defense Applications",
    date: "2025-12-10",
    readTime: "6 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "delivery-drones-logistics",
    title: "Delivery Drones: The Future of Logistics",
    excerpt: "Revolutionizing last-mile delivery with autonomous aerial vehicles for e-commerce and emergency medical supplies.",
    category: "Drone Technology",
    branch: "Delivery Drones",
    date: "2025-12-05",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1520695287272-b7f8af46d367?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "drone-maintenance-repair",
    title: "Drone Maintenance & Repair: Ensuring Operational Excellence",
    excerpt: "Best practices for drone fleet management, preventive maintenance schedules, and troubleshooting common issues.",
    category: "Drone Technology",
    branch: "Drone Maintenance",
    date: "2025-11-28",
    readTime: "6 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "thermal-imaging-drones",
    title: "Thermal Imaging Drones: Beyond Visual Spectrum",
    excerpt: "Applications of thermal cameras in drones for wildlife monitoring, electrical inspections, and search operations.",
    category: "Drone Technology",
    branch: "Thermal Imaging",
    date: "2025-11-22",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1563968743333-044cef800494?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "agricultural-spraying-drones",
    title: "Agricultural Spraying Drones: Precision Application Systems",
    excerpt: "Optimizing pesticide and fertilizer distribution with GPS-guided drone sprayers for reduced waste and enhanced coverage.",
    category: "Drone Technology",
    branch: "Agricultural Spraying",
    date: "2025-11-18",
    readTime: "6 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=900&h=600&fit=crop&auto=format",
  },

  // CLOUD COMPUTING (13 posts)
  {
    id: "cloud-architecture-design",
    title: "Cloud Architecture: Designing Scalable Systems",
    excerpt: "Master the fundamentals of cloud infrastructure design, microservices architecture, and high-availability patterns.",
    category: "Cloud Computing",
    branch: "Cloud Architecture",
    date: "2026-01-14",
    readTime: "8 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "hybrid-cloud-strategies",
    title: "Hybrid Cloud Strategies: Best of Both Worlds",
    excerpt: "Balancing on-premise and cloud resources for optimal performance, security, and cost efficiency.",
    category: "Cloud Computing",
    branch: "Hybrid Cloud",
    date: "2026-01-11",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "multi-cloud-management",
    title: "Multi-Cloud Management: Avoiding Vendor Lock-In",
    excerpt: "Strategies for managing workloads across AWS, Azure, and GCP while maintaining interoperability and resilience.",
    category: "Cloud Computing",
    branch: "Multi-Cloud Strategy",
    date: "2026-01-07",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "cloud-migration-guide",
    title: "Cloud Migration: From On-Premise to Cloud-Native",
    excerpt: "Step-by-step guide to successful cloud migration including assessment, planning, execution, and optimization.",
    category: "Cloud Computing",
    branch: "Cloud Migration",
    date: "2026-01-04",
    readTime: "9 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "devops-cicd-pipelines",
    title: "DevOps & CI/CD: Accelerating Cloud Deployments",
    excerpt: "Implementing continuous integration and deployment pipelines for rapid, reliable cloud application releases.",
    category: "Cloud Computing",
    branch: "DevOps & CI/CD",
    date: "2025-12-29",
    readTime: "8 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "cloud-ai-services",
    title: "Cloud AI Services: Machine Learning at Scale",
    excerpt: "Leveraging cloud-native AI platforms for training, deploying, and scaling machine learning models efficiently.",
    category: "Cloud Computing",
    branch: "Cloud AI Services",
    date: "2025-12-24",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "edge-cloud-computing",
    title: "Edge Cloud Computing: Distributed Intelligence",
    excerpt: "Bringing compute resources closer to data sources for ultra-low latency applications and IoT workloads.",
    category: "Cloud Computing",
    branch: "Edge Cloud",
    date: "2025-12-19",
    readTime: "6 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "cloud-cost-optimization",
    title: "Cloud Cost Optimization: Maximizing ROI",
    excerpt: "Proven techniques to reduce cloud spending through resource rightsizing, reserved instances, and automation.",
    category: "Cloud Computing",
    branch: "Cloud Cost Optimization",
    date: "2025-12-14",
    readTime: "8 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "serverless-computing",
    title: "Serverless Computing: Event-Driven Architecture",
    excerpt: "Build scalable applications without managing servers using AWS Lambda, Azure Functions, and similar platforms.",
    category: "Cloud Computing",
    branch: "Serverless Computing",
    date: "2025-12-09",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "cloud-for-startups",
    title: "Cloud for Startups: Rapid Infrastructure Deployment",
    excerpt: "How startups leverage cloud infrastructure for rapid prototyping, scaling, and cost-effective growth.",
    category: "Cloud Computing",
    branch: "Cloud for Startups",
    date: "2025-12-04",
    readTime: "6 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "cloud-security-best-practices",
    title: "Cloud Security: Protecting Data in the Cloud",
    excerpt: "Comprehensive security strategies including encryption, identity management, and compliance frameworks.",
    category: "Cloud Computing",
    branch: "Cloud Security",
    date: "2025-11-30",
    readTime: "8 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "kubernetes-container-orchestration",
    title: "Kubernetes & Container Orchestration",
    excerpt: "Mastering Kubernetes for deploying, scaling, and managing containerized applications in production.",
    category: "Cloud Computing",
    branch: "Container Orchestration",
    date: "2025-11-26",
    readTime: "9 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1605745341112-85968b19335b?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "cloud-native-development",
    title: "Cloud-Native Development: Building Modern Applications",
    excerpt: "Designing applications optimized for cloud environments with 12-factor principles and microservices patterns.",
    category: "Cloud Computing",
    branch: "Cloud-Native Development",
    date: "2025-11-21",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=900&h=600&fit=crop&auto=format",
  },

  // LMS & EDTECH (13 posts)
  {
    id: "ai-based-lms",
    title: "AI-Based LMS: Personalized Learning Experiences",
    excerpt: "How AI algorithms adapt content delivery, recommend resources, and optimize learning paths for individual students.",
    category: "LMS & EdTech",
    branch: "AI-Based LMS",
    date: "2026-01-13",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "personalized-learning-platforms",
    title: "Personalized Learning: Adaptive Education Platforms",
    excerpt: "Tailoring educational content to learner pace, style, and proficiency using data-driven insights.",
    category: "LMS & EdTech",
    branch: "Personalized Learning",
    date: "2026-01-09",
    readTime: "6 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "virtual-labs-education",
    title: "Virtual Labs: Hands-On Learning in Digital Spaces",
    excerpt: "Simulated laboratory environments enabling students to conduct experiments remotely with realistic outcomes.",
    category: "LMS & EdTech",
    branch: "Virtual Labs",
    date: "2026-01-02",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "skill-tracking-systems",
    title: "Skill Tracking Systems: Measuring Learning Outcomes",
    excerpt: "Advanced analytics platforms for monitoring student progress, competency development, and knowledge retention.",
    category: "LMS & EdTech",
    branch: "Skill Tracking",
    date: "2025-12-27",
    readTime: "6 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "online-certification-platforms",
    title: "Online Certification Platforms: Credentialing the Future",
    excerpt: "Blockchain-verified certifications and digital badges for professional skills and academic achievements.",
    category: "LMS & EdTech",
    branch: "Online Certification",
    date: "2025-12-23",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "lms-analytics-insights",
    title: "LMS Analytics: Data-Driven Education Insights",
    excerpt: "Leveraging learning analytics dashboards to improve course design, engagement, and student success rates.",
    category: "LMS & EdTech",
    branch: "LMS Analytics",
    date: "2025-12-17",
    readTime: "8 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "gamification-lms",
    title: "Gamification in LMS: Engagement Through Play",
    excerpt: "Incorporating game mechanics like points, badges, and leaderboards to boost motivation and participation.",
    category: "LMS & EdTech",
    branch: "Gamification",
    date: "2025-12-13",
    readTime: "6 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "corporate-training-systems",
    title: "Corporate Training Systems: Enterprise Learning Platforms",
    excerpt: "Scalable LMS solutions for employee onboarding, compliance training, and continuous professional development.",
    category: "LMS & EdTech",
    branch: "Corporate Training",
    date: "2025-12-07",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "lms-for-institutions",
    title: "LMS for Educational Institutions: Campus-Wide Solutions",
    excerpt: "Comprehensive platforms managing courses, assessments, grading, and communication for schools and universities.",
    category: "LMS & EdTech",
    branch: "LMS for Institutions",
    date: "2025-12-01",
    readTime: "8 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=900&h=600&fit=crop&auto=format&auto=format",
  },
  {
    id: "ar-vr-education",
    title: "AR/VR in Education: Immersive Learning Technologies",
    excerpt: "Transforming education with augmented and virtual reality for interactive simulations and experiential learning.",
    category: "LMS & EdTech",
    branch: "AR/VR in Education",
    date: "2025-11-27",
    readTime: "9 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "mobile-learning-platforms",
    title: "Mobile Learning: Education On-The-Go",
    excerpt: "Responsive LMS design and mobile-first strategies for learning anytime, anywhere on any device.",
    category: "LMS & EdTech",
    branch: "Mobile Learning",
    date: "2025-11-23",
    readTime: "6 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "collaborative-learning",
    title: "Collaborative Learning Platforms: Social Education",
    excerpt: "Peer-to-peer learning features including discussion forums, group projects, and real-time collaboration tools.",
    category: "LMS & EdTech",
    branch: "Collaborative Learning",
    date: "2025-11-19",
    readTime: "7 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=900&h=600&fit=crop&auto=format",
  },
  {
    id: "lms-api-integration",
    title: "Learning Management API Integration: Ecosystem Connectivity",
    excerpt: "Integrating LMS platforms with existing enterprise systems, payment gateways, and third-party content providers.",
    category: "LMS & EdTech",
    branch: "LMS Integration",
    date: "2025-11-15",
    readTime: "8 min read",
    author: "Karvensen Team",
    heroImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=900&h=600&fit=crop&auto=format",
  },
]

